### ISSUE TITLE
Licence 

### ISSUE THREAD

**Issue by mgifford** [evilmartians/oklch-picker#106]
What licence is the code under? MIT?

**Comment by ai** [comment]
Yes https://github.com/evilmartians/oklch-picker/blob/main/LICENSE

**Comment by ai** [comment]
Do you want to integrate it somewhere? Maybe we can help?

**Comment by mgifford** [comment]
Cool. I mostly just wanted to highlight it here [https://accessibility.civicactions.com/guide/tools#color](https://accessibility.civicactions.com/guide/tools#color)  
  
Seems like a good approach. I don't know color well, but can collect tools that do.  
  
There was a color contrast tool using this approach to color.
