### ISSUE TITLE
Auto calc the Hue outside 0—360 degrees

### ISSUE THREAD

**Issue by romashamin** [evilmartians/oklch-picker#118]
Since the Hue represents a color wheel, let’s recalc the input accordingly:

- 375 should become 15
- -15 should become 345

<img width="412" alt="image" src="https://github.com/evilmartians/oklch-picker/assets/1148914/7fb8ca70-062a-4241-a9d7-1f5b608dc49e">

**Comment by ai** [comment]
@raidenmiro can I ask you to tune it?
