### ISSUE TITLE
Maximizing chroma or lightness

### ISSUE THREAD

**Issue by CHRIBUR0309** [evilmartians/oklch-picker#126]
I want to do that:

1. Determine color gamut.
2. Fix hue and lightness.
3. Maximize chroma.

or,

1. Determine color gamut.
2. Fix hue and chroma.
3. Maximize lightness.

I want a button that calculates the maximum possible values for chroma or lightness with one click.

**Comment by ai** [comment]
Yes, it could be a popular use case. We will think about the best UX.

**Comment by ai** [comment]
We added a plan for UI. Please follow this issue https://github.com/evilmartians/oklch-picker/issues/130
