### ISSUE TITLE
Validation issues in lightness, chroma, hue

### ISSUE THREAD

**Issue by siukalov** [evilmartians/oklch-picker#132]
These fields allow text input:

<img width="885" alt="image" src="https://github.com/evilmartians/oklch-picker/assets/7101606/91cb08b3-1bde-49ca-8767-c39a39cc8c32">

Compare with the alpha field:

<img width="561" alt="image" src="https://github.com/evilmartians/oklch-picker/assets/7101606/336b2bb5-c581-4297-a093-f4286ae66a44">

**Comment by ai** [comment]
Thanks for the report.

Fixed 31101fa
