### ISSUE TITLE
Formula to convert okchl

### ISSUE THREAD

**Issue by ivofernandes** [evilmartians/oklch-picker#136]
Amazing project :) 

Where can I find in the project the code that is used to convert lch to rgb?

**Comment by ai** [comment]
I am using `culori` and recommend just it if you are having JS project: `rgb(oklch(color))`

If you have another language, you can use math from OKLCH announce article (note that this math is to *linear RGB*, you may need second step to convert to normal RGB).
https://bottosson.github.io/posts/oklab/#converting-from-linear-srgb-to-oklab
