### ISSUE TITLE
`Home` and `End` don't follow input standards

### ISSUE THREAD

**Issue by adrian5** [evilmartians/oklch-picker#137]
I use both to jump within the input while entering digits and their non-standard behavior in the web app always catches me off-guard. I don't think it's a good idea to hijack something long standardized like this.

**Comment by ai** [comment]
We have custom input fields because we need to handle math expressions in the fields https://github.com/evilmartians/oklch-picker/issues/74

Can you send PR with these buttons handling to this file? https://github.com/evilmartians/oklch-picker/blob/main/view/field/index.ts

**Comment by adrian5** [comment]
I see, that makes sense. Wasn't even aware of the math expression support.

I'm too busy right now to dive into this right now, I think it would be better if someone familiar with the project added them. As you probably know, `Home` moves the cursor to the start of a line (or input field) and `End` to its end.

**Comment by ai** [comment]
@raidenmiro seems like we forget for `End` and `Home`

**Comment by ai** [comment]
Fixed 768c71c

**Comment by adrian5** [comment]
Awesome, that does it. Thanks!
