### ISSUE TITLE
Add Snapping Toggle

### ISSUE THREAD

**Issue by Tumbolisu** [evilmartians/oklch-picker#138]
I wish I could move the sliders without them snapping to anything. That way I can choose colors with more precision.
Adding a new toggle to enable/disable the snapping behavior would make me happy.

**Comment by ai** [comment]
Sure, we are thinking about the design.

For now, you can use text fields arrows to change values without snapping.

**Comment by ai** [comment]
Sorry, we decided that extra settings will make UI too complex and text fields are for previes control
