### ISSUE TITLE
Add linear-rgb display format

### ISSUE THREAD

**Issue by george-steel** [evilmartians/oklch-picker#139]
Linear sRGB (not gamma-encoded) color values are required by many 3D rendering pipelines in OpenGL and similar APIs. Please add this format to the available display formats as well as the CSS formats.

An example, the CSS color `#808080ff` would correspond to the OpenGL color `vec4(0.21586, 0.21586, 0.21586, 1.0)`.

**Comment by ai** [comment]
Good idea. I will try to do it on this week.

**Comment by ai** [comment]
Done https://github.com/evilmartians/oklch-picker/commit/d5a199ffce09cec0287f7ee3af4b3caa7d1617a1

**Comment by george-steel** [comment]
I tried it out and it does not work for all colors. Reopened with details of the bug at #140
