### ISSUE TITLE
Linear RGB format loses all precision below luminance of about 20%

### ISSUE THREAD

**Issue by george-steel** [evilmartians/oklch-picker#140]
Due to the rounding method used, the linear RGB display format does not output correctly at low luminance values. Below about 10% luminance, the displayed values get rounded to zero. Please adjust the rounding so that components show at least 3 significant digits even on very low values.

**Comment by ai** [comment]
I have exactly 3 digits in round function.

Can you show some example? Maybe we have a bug?

**Comment by george-steel** [comment]
If your rounding function only supports rounding to a fixed number of digits, rounding to 5 digits instead of 3 digits would make the conversion work for nearly all colors.

**Comment by ai** [comment]
I changed digits count https://github.com/evilmartians/oklch-picker/commit/9d65b5bdca1a16a11543df85211329847ddacd03

Can you test?

**Comment by george-steel** [comment]
Works for me. Thanks for fixing it.
