### ISSUE TITLE
When having a concurrency count above 20 in Chrome First graph to update from user input breaks

### ISSUE THREAD

**Issue by thethinur** [evilmartians/oklch-picker#141]
Like the title says, when you first load the site the first graph that changes from user input breaks.
Play with Hue slider; Lightness graph wont update for rest of the session
Play with Lightness slider; Chroma graph wont update... 
Play with Chroma; Hue Graph wont update...

Once one graph breaks the others will work just fine. 

Everything else will work just fine for the session.

Google Chrome 123.0.6312.59 and 123.0.6312.86 
Windows 11 22631.3296
Intel i7-13700F 16 Cores, 24 Threads
Nvidia RTX 3070 running 546.01 and 551.86

Works correctly on Chrome running on a Samsung Galaxy Tab S8 Ultra 

Chrome and Nvidia Driver got updated. No change. 

Works fine on Firefox.

**Comment by thethinur** [comment]
Doesn't replicate on a s8 ultra with latest Chrome, so might be a quirk of a graphics driver.

**Comment by ai** [comment]
Can you record a video?

Website works find on my machine.

**Comment by thethinur** [comment]
Yes, of course: 
https://github.com/evilmartians/oklch-picker/assets/7808616/ad0bfcd2-82bf-4277-9b07-b2433ac67fac

**Comment by ai** [comment]
Show the console. If it is empty, it is video glitch.

**Comment by thethinur** [comment]
Only happens on the first one.

**Comment by ai** [comment]
This error could block the construction of the graph.

But I have no idea why you have it and I don't.

Let's wait for more reports.

**Comment by thethinur** [comment]
At least what is clear is it's failing when creating a new ImageData(), if I could just check variables I could at least see what might be wrong.

**Comment by thethinur** [comment]
![image](https://github.com/evilmartians/oklch-picker/assets/7808616/9b0f951d-a813-4ef8-b269-42509b644f85)

There is wrong data in the first event, might be an initialization error.

![image](https://github.com/evilmartians/oklch-picker/assets/7808616/fce61d74-507e-4b20-af28-efcb74c81f16)

Yeah, first onmessage event after loading the page is wrong. 
Unexpected data during page-load? 
Could it relate to loading speed? 
Like polling some data that changes post-load?

**Comment by thethinur** [comment]
Clearer picture of the stack.
![image](https://github.com/evilmartians/oklch-picker/assets/7808616/e02900c2-d39b-4664-b057-a8442c5f9aba)

**Comment by thethinur** [comment]
Ok, it's a chromium error in general on my machine, because Edge fails too. If I should take a stab in the dark, I'd guess it's chromium scheduling playing games due to my PC being way overkill.

**Comment by thethinur** [comment]
Ayy, I might have isolated the issue. Okay, there might be a logic error looming inside the workers. I limited concurrency and it works normally for all 20 and under, but above 20 the site might break. 
21: Original Error but e.data.from is always 341
22: Site works as normal
23: An index error appears, but site continues to work as normal.
24: Original Error

**Comment by ai** [comment]
1. What is your screen size and scale (100%/150%/200%)? Show `window.devicePixelRatio`.
2. How many CPU cores do you have? Show `navigator.hardwareConcurrency`

**Comment by thethinur** [comment]
![image](https://github.com/evilmartians/oklch-picker/assets/7808616/ce218446-0c49-4aa2-9310-40600f1e268a)

**Comment by thethinur** [comment]
I have 16 Cores and 24 Threads.

Firefox picks Core count for hardwareConcurrency.
![image](https://github.com/evilmartians/oklch-picker/assets/7808616/88e04021-3d31-47eb-9f53-b09f575c45eb)
Chrome picks Thread count for hardwareConcurrency.
![image](https://github.com/evilmartians/oklch-picker/assets/7808616/7c5c8b52-6b93-4d26-ae85-84134eba638a)

It's definitely scheduling playing games, but that also means in the end, there is most a logic error too, because this is definitely a race-condition. Something is running earlier or later and changing the outcome, at least it's consistent.

**Comment by ai** [comment]
I was able to reproduce an error. Wait a little for a fix.

**Comment by thethinur** [comment]
That's great. I was too unfamiliar with your tooling and JS + TS in general or I might have just tried a few things and made a pull request.

**Comment by ai** [comment]
Should be fixed https://github.com/evilmartians/oklch-picker/commit/8e089e831c2dcb3631d417cf8846b762c85906f9

Can you try?

**Comment by thethinur** [comment]
Works like a charm. Closing
