### ISSUE TITLE
oklch(100% 0 0) shows as unavailable on any device

### ISSUE THREAD

**Issue by dgtlntv** [evilmartians/oklch-picker#165]
When I enter `oklch(100% 0 0)` it shows as unavailable on any device (see screenshot)
![Screenshot 2024-11-21 at 14 47 36](https://github.com/user-attachments/assets/c48a0a4d-e240-4652-be9f-7bd5f43cfa45)

When I enter `#FFFFFF` it shows as a P3 color and gives an unexpected oklch value: `oklch(100% 3.5594404384177905e-8 106.37411429114086)`
![Screenshot 2024-11-21 at 14 47 57](https://github.com/user-attachments/assets/d1a9967c-baec-448d-8fd9-15bb75e4b9a0)

**Comment by ai** [comment]
Yes, seems like a bug. 

I will try to research soon.

**Comment by dgtlntv** [comment]
Awesome, thanks! :)

**Comment by ai** [comment]
I added a hack 93bc93911e27e5c60880e7f9cd00d8912791105e
