### ISSUE TITLE
Regression in 65d5ec5: Graphs are no longer visible

### ISSUE THREAD

**Issue by zheland** [evilmartians/oklch-picker#166]
## Summary

After yesterday's commit 65d5ec5a1cdb4fb1dead72135220b6a632bcae7c graphs are no longer visible. 

## Details

- Canvas node is present.
- Guides on graph canvas are visible.
- Colorbars below the graphs are visible.
- Colored graph canvas content isn't visible.
- Black borders separating color spaces on graph canvas aren't visible.

Graphs works completely fine for the commit before 65d5ec5a1cdb4fb1dead72135220b6a632bcae7c: c038ccf2bfacc7a2ec47ac8024e3ab725c924db9

Broken for any commit after 65d5ec5a1cdb4fb1dead72135220b6a632bcae7c including: 26eb02aed787a74596439048c7ab995eaf8a4d56, 93bc93911e27e5c60880e7f9cd00d8912791105e, 0b3694c1fc2878ce1237fedd2758f7f08a68937a.

## Screenshots

Before 65d5ec5a1cdb4fb1dead72135220b6a632bcae7c:
![c038ccf](https://github.com/user-attachments/assets/ed964691-e4b9-4665-801c-16c321630807)

After 65d5ec5a1cdb4fb1dead72135220b6a632bcae7c:
![65d5ec5](https://github.com/user-attachments/assets/bbd91345-3a15-4f18-b4a9-c44661303a51)

## Reproduction

```
git clone git@github.com:evilmartians/oklch-picker.git
cd oklch-picker
pnpm install
pnpm start
# Graphs not visible

git reset --hard c038ccf2bfacc7a2ec47ac8024e3ab725c924db9
pnpm start
# Graphs works fine

git reset --hard 65d5ec5a1cdb4fb1dead72135220b6a632bcae7c
pnpm start
# Graphs not visible
```

Reproduced in:
- Firefox 132.0.2 (64-bit) (Linux)
- Chrome 128.0.6613.119 (64-bit) (Linux)
- Firefox 133.0 (64-bit) (Windows)
- Chrome 131.0.6778.82 (Android)

## Workaround

```
git clone git@github.com:evilmartians/oklch-picker.git
cd oklch-picker
git reset --hard c038ccf2bfacc7a2ec47ac8024e3ab725c924db9
pnpm install
pnpm start
```

**Comment by ai** [comment]
Thanks. Fixed 1b2730a
