### ISSUE TITLE
Add buttons to text fields

### ISSUE THREAD

**Issue by ai** [evilmartians/oklch-picker#17]
We need `copy` button near `oklch()` and `rgba()` fields and `←`/`→` buttons for `L`/`C`/`H`/`A` fields,

**Comment by djmtype** [comment]
I'm not sure how helpful this plugin is if you can't copy/paste the entire value. 
The online tool is so awesome by comparison! https://oklch.com/

**Comment by ai** [comment]
@djmtype this is repo of https://oklch.com/

**Comment by djmtype** [comment]
Whoops! Sorry @ai
