### ISSUE TITLE
Work with hotkeys on different keyboard layouts

### ISSUE THREAD

**Issue by ai** [evilmartians/oklch-picker#32]
1. Switch to Russian layout
2. Press `L` (`Д`)

Expected result: L field focus.

Current result: no focus.

**Comment by redly** [comment]
You could try to replace `e.key` inside keydown events with `e.code` which will return `KeyL` (for your example) value for all different layouts. `e.code` value is not affected by the current keyboard layout or modifier state, so it will always return the same value

And 

```js
let hotkey = field.querySelector('kbd')!.innerText.trim().toLowerCase()
hotkeys[hotkey] = input
```

could be replaced by 

```js
let hotkey = `Key${field.querySelector('kbd')!.innerText.trim().toUpperCase()}`
hotkeys[hotkey] = input
```

**Comment by ai** [comment]
@redly can you try to send PR to save your name in the project’s history?

**Comment by redly** [comment]
> @redly can you try to send PR to save your name in the project’s history?

@ai Open a new PR #40 with bug fix

**Comment by ai** [comment]
@redly do you have Twitter account to mention you?
