### ISSUE TITLE
`<input type="number">` bug in Chrome

### ISSUE THREAD

**Issue by ai** [evilmartians/oklch-picker#36]
https://twitter.com/4rontender/status/1524789019728568320

https://user-images.githubusercontent.com/19343/168473841-03d0f5ca-f738-4cc6-bd3f-4df47a3105c8.mp4

**Comment by maikudou** [comment]
Can reporduce in
- Safari Technology Preview Release 145 (Safari 15.4, WebKit 17614.1.11.6)
- Safari Version 15.5 (17613.2.7.1.8)

**Comment by moledart** [comment]
Hello guys. I don't really know how to branch and stuff, but i found the bug.

It's in here oklch-picker-main\view\field\index.ts

`function onMouseUp(e: MouseEvent): void {
  e.preventDefault()
  let input = e.target as HTMLInputElement
  input.removeEventListener('mouseup', onMouseUp)
}`

`function onFocus(e: FocusEvent): void {
  let input = e.target as HTMLInputElement
  input.select()
  input.addEventListener('mouseup', onMouseUp)
  setTimeout(() => {
    input.addEventListener('mouseup', onMouseUp)
  }, 500)
}`

Just need to replace 'mouseup' with 'click' in every EventListener.
Sorry if i'm doing it wrong it's my first time.

**Comment by ai** [comment]
Hm. We have this hack to prevent zoom on iPhone.

I will think how to avoid the problem.

**Comment by ai** [comment]
One of possible solution 8801f53

**Comment by ai** [comment]
The Chome bug was fixed. I will try to find iPhone tomorrow to check that iPhone hack is still active.

**Comment by ai** [comment]
Nope, that fix brought `select all` bug back to Safari.

Another way: f4158b5
