### ISSUE TITLE
Add apple-touch-icon

### ISSUE THREAD

**Issue by QuarkPixel** [evilmartians/oklch-picker#61]
Add an apple-touch-icon so that when user add this website to Home Screen can display the logo instead of webpage screenshot.

![IMG_27AFEE04E106-1](https://user-images.githubusercontent.com/65812149/210164600-c43d9af0-85e8-44e2-b311-97ea6bbff1e8.jpeg)

Example:
<head>
  <link rel="apple-touch-icon" href="xxx" />
</head>

**Comment by ai** [comment]
Hm, we have an Apple icon and `<link>` tag with [correct URL](https://oklch.com/apple-touch-icon-oklch-be29b3e7.png):

```html
<link rel="apple-touch-icon" href="/apple-touch-icon-oklch-be29b3e7.png"/>
```

The image size is 180×180.

1. What iOS do you have?
2. Any idea why it doesn’t work?

**Comment by QuarkPixel** [comment]
I just tried again, and now it's working properly. It's a little strange, but I think it may be Sarari browser or my problem. Anyway, sorry to bother you 😂
