### ISSUE TITLE
Fallback colour location?

### ISSUE THREAD

**Issue by nclm** [evilmartians/oklch-picker#67]
When picking a colour outside of the available colour space, the Fallback frame appears, which is helpful!

It would also be great to show what exactly is the fallback colour?

Possibilities:

- A small dot or similar could be shown on each of the three pickers where the current selection is out of the possible colour range, just showing where the fallback is actually going?

- Clicking on the Fallback frame could update the picker to select this colour?

**Comment by ai** [comment]
> Clicking on the Fallback frame could update the picker to select this colour?

I like this one as the safe option. Do you want to send PR?

**Comment by ai** [comment]
Done a076fb1
