### ISSUE TITLE
Некорректная обработка ввода rgb() в синей области

### ISSUE THREAD

**Issue by dom1n1k** [evilmartians/oklch-picker#73]
Если в нижнее поле ввести `rgb(255, 0, 0)`, то всё работает нормально:

![oklch-red-255](https://user-images.githubusercontent.com/1683168/219099833-c4da4975-9393-439c-b264-1ccb334c317d.png)

Если ввести `rgb(0, 255, 0)`, тоже нормально:

![oklch-green-255](https://user-images.githubusercontent.com/1683168/219100089-2ac24279-fff0-4fdd-a8b6-4a87c0455312.png)

Но если ввести `rgb(0, 0, 255)` то после нажатия Enter цвет слетает в `rgb(0, 49, 229)`:

![oklch-blue-255](https://user-images.githubusercontent.com/1683168/219100103-1bc6836d-0283-4422-be5d-80b8693c7b8a.png)

Конечно, сразу возникает подозрение на out of gamut. Поскольку цвета крайние, им достаточно даже небольших погрешностей floating-point арифметики.
Однако ситуация повторяется и для менее ярких синих:
`rgb(0, 0, 200)` заменяется на `rgb(0, 36, 179)`
`rgb(0, 0, 100)` заменяется на `rgb(0, 13, 89)`

Проблема также проявляется для циана и фиолетового, хотя и в меньшей степени:
`rgb(0, 255, 255)` заменяется на `rgb(1, 255, 255)`
`rgb(255, 0, 255)` заменяется на `rgb(255, 2, 255)`

Что-то похожее есть и в P3:
`color(display-p3 0 0 0.999)` выводит сообщение `Rec2020 is unavailable on this device`, хотя этот цвет совершенно точно внутри P3.

Я посмотрел код, и кажется, что проблема (точнее даже две) тут:
https://github.com/evilmartians/oklch-picker/blob/a2eb439221990240d335ca185e84bf894d98d2fc/stores/current.ts#L190-L206

### Первая проблема
Использование `clampChroma`. Это очень простой метод гамут-мэппинга: если смотреть на диаграмме Chroma, то любая точка из белой области просто опускается вертикально вниз до ближайшего цвета. Во многих ситуациях это работает приемлемо, но не всегда.

Обратите внимание на скриншоты выше.
`rgb(255, 0, 0)` и `rgb(0, 255, 0)` стоят на пиках, как и должны, а `rgb(0, 0, 255)` (вернее то, что от него осталось) сполз вниз.
Разница в том, что у красного и зеленого пиков склоны пологие. Даже если цвет немного сместился в сторону, `clampChroma` приземлит его где-то рядом.
У синего пика левый склон отвесный, поэтому даже микроскопическое отклонение за левую границу даст большое перемещение вниз — цвет фактически падает в ущелье. Я немного потестил Culori, там обычные арифметические погрешности в 14-15 знаке.
А, например, `rgb(10, 0, 255)` работает корректно. Это потому, что небольшая добавка красного сдвигает цвет правее, с отвесного склона на пологий.

Вообще, это известная проблема. В экстремальных случаях синий цвет даже может образовывать такой шип:
<img src="http://www.brucelindbloom.com/images/WS09.gif">
Если здесь из точки (0, 0) провести радиус-вектор (а это и есть хрома) в верхушку шипа, он сначала выйдет из ЦП, а потом войдет обратно. Но это крайность, в популярных ЦП такого нет.
Тем не менее, сложности с поверхностями под неудобными углами имеются (см. например книгу Моровица).

К сожалению, простого выхода тут нет. Скорее всего, придется подпирать синий цвет каким-то костылём.

### Вторая проблема
Округление значения `accurate`.
Понятно, что пользователю не нужны 15 знаков после запятой. Но опасно использовать округленное значение в качестве эталона — иногда небольшие изменения в одной модели дают ощутимые сдвиги в другой. Возможно, стоило бы иметь точное значение для внутренних вычислений и для урла, а округлять на уровне UI. А если это сложно, то я бы рекомендовал увеличить точность, хотя бы на 1 знак.

**Comment by ai** [comment]
Скорее всего проблема в том, что `clampChroma()` в `culori` использует LCH, а не OKLCH (плюс у LCH есть проблема в синем).

Всё немного усложняется тем, что все библиотеки работы с цветом плохие и ни одна не решает наши задачи. Видимо нормальное решение проблемы — написать свой алгоритм гамма-мапинга через OKLCH (может быть можно портировать из `postcss-preset-env`?).

**Comment by dom1n1k** [comment]
> Скорее всего проблема в том, что `clampChroma()` в `culori` использует LCH, а не OKLCH

Нет, сulori умеет оба варианта:
https://culorijs.org/api/#clampChroma

И у вас это обрабатывается:
https://github.com/evilmartians/oklch-picker/blob/a2eb439221990240d335ca185e84bf894d98d2fc/stores/current.ts#L197

Самое смешное, как раз в LCH отсечение синего работает корректно:
https://lch.oklch.com/#29.568297153444703,131.1854613942089,301.36428148973533,100

Но зато полная катастрофа с желтым:
`rgb(255, 255, 0)` сваливается в `rgb(255, 250, 192)`
https://lch.oklch.com/#97.60701009682253,29.16982349640181,99.57226374240976,100

Причина всё та же: там, где график хромы имеет пологие склоны, всё хорошо, а где отвесная вертикаль — плохо.

Я также немного потестил culori отдельно, и пока что каких-то явных багов не нашел. Некорректная работа `clampChroma` это не баг реализации, а фундаментальная проблема самого подхода.

Получается, что отсечение в LCH может стать тем самым костылем для синего :)

**Comment by dom1n1k** [comment]
> может быть можно портировать из postcss-preset-env?

Я посмотрел: https://github.com/csstools/postcss-plugins/blob/main/packages/color-helpers/src/calculations/binary-search-gamut.ts
Это упрощенная вариация известного [алгоритма из спецификации W3C](https://www.w3.org/TR/css-color-4/#binsearch).
В целом да, это оно. Но есть смутное подозрение, что эта версия не совсем корректна. Пока не понял всех деталей.

Можно общее решение отложить на подумать, а починить крайние цвета, которые вываливаются банально из-за арифметических погрешностей. Достаточно [добавить погрешность](https://github.com/csstools/postcss-plugins/blob/main/packages/color-helpers/src/utils/in-gamut.ts).

**Comment by ai** [comment]
Давай попробуем. Отправляй PR.

**Comment by ai** [comment]
А почему после PR `#0000ff` отображается как P3-цвет?

![Captura desde 2023-02-20 09-42-31](https://user-images.githubusercontent.com/19343/220055596-e424f378-207f-4ecf-97dd-c8aaa83e790d.png)

**Comment by ai** [comment]
Я пока откатил исправление, так как неточное конвертирование RGB→OKLCH меньшая проблема, чем врущие графики

**Comment by dom1n1k** [comment]
> А в LCH вообще Rec2020: https://lch.oklch.com/#29.57,131.2,301.36,100

Конкретно этот случай – из-за округлений координат LCH. Если убираю округления, становится правильно. То есть это было и раньше, но маскировалось изменением цвета, которое делала `clampChroma`.

> А почему после PR #0000ff отображается как P3-цвет?

Тут сложнее. Мне кажется, это тоже было раньше и маскировалось изменением цвета.
Почему я так думаю – проблема проявляется только в узком диапазоне оттенков между чисто-синим и голубовато-синим. И этот диапазон подозрительно похож на тот, где проявляется #62. Кажется, где-то сидит мелкий арифметический баг, но пока что найти не получилось.

Кроме того. Я не учел, что гамут проверяется ещё в нескольких местах. Я смотрел вызовы функций, а тут заинлайнено.  Думаю, можно заменить на вызовы, потому что экономии нет – конвертация все равно делается чуть выше.
https://github.com/evilmartians/oklch-picker/blob/8b37f8ad1207b072daf1d4a0f11d6290e0d88251/lib/colors.ts#L226-L242

P.S. Оффтоп: очень долго не получалсь развернуть проект локально, потому что сыпались ошибки пакетов, связанных с culori (там по какой-то причине завязка на конкретную версию). Пробовал pnpm/npm/yarn, ничего не работало. Удалось собрать только вручную заменив culori на свежую. Хотя все равно TS ругается на нехватку типов.

**Comment by ai** [comment]
> Оффтоп: очень долго не получалсь развернуть проект локально, потому что сыпались ошибки пакетов, связанных с culori (там по какой-то причине завязка на конкретную версию). Пробовал pnpm/npm/yarn, ничего не работало. Удалось собрать только вручную заменив culori на свежую. Хотя все равно TS ругается на нехватку типов.

Сейчас исправлю

**Comment by ai** [comment]
Исправил сборку, убрав форк `culori` 3dd6cbf

Жду другого PR, который добавит эпсилон и в других местах?

**Comment by ai** [comment]
Создал другой ишью по новому багу конвертации https://github.com/evilmartians/oklch-picker/issues/78
