### ISSUE TITLE
Incorrectly reporting P3 unavailable

### ISSUE THREAD

**Issue by argyleink** [evilmartians/oklch-picker#89]
in Chrome 111

![Screenshot 2023-03-16 at 9 44 09 AM](https://user-images.githubusercontent.com/1134620/225691715-e5fae059-11ee-46e7-bbfc-2738baeb818f.png)

that's a p3 pink on that box, yet the tool is reporting it's not available. not sure how you're checking support, but looks like it needs an update.

thanks y'all! tool is great.

**Comment by ai** [comment]
Do you have P3 monitor?

We are using [`@media (color-gamut:p3)` and `@supports (color: oklch(100% 0 0))`](
https://github.com/evilmartians/oklch-picker/blob/main/stores/support.ts#L14-L20). I worked in Chrome on Mac with P3 screen (but doesn’t work on Pixel 6, I thought it has OLED P3 screen).

**Comment by argyleink** [comment]
ah yep, was on the srgb monitor!

<img width="501" alt="Screenshot 2023-03-16 at 10 15 37 AM" src="https://user-images.githubusercontent.com/1134620/225699719-f9576e99-2dad-4495-bc04-8ac511fb186b.png">

**Comment by argyleink** [comment]
great idea, that would def have tipped me off into the why 💯

**Comment by ai** [comment]
Fixed 5cc883c

**Comment by argyleink** [comment]
Swift work yo! I gave it a quick spin, here's some results:

I expected to get a message in this first screenshot, that the screen didnt support it because the browser does. But instead, I got a message that it's unavailable in the browser.

<details><summary>Screen <b>without</b> wide gamut, Browser does support it</summary>
<p>

![Screenshot 2023-03-17 at 7 35 13 AM](https://user-images.githubusercontent.com/1134620/225935279-5d265bee-0efd-4592-87ac-b5e823152476.png)

</p>
</details> 

<details><summary>Screen <b>with</b> wide gamut, Browser does support it too</summary>
<p>

<img width="501" alt="Screenshot 2023-03-17 at 7 35 18 AM" src="https://user-images.githubusercontent.com/1134620/225935493-9e20e6bc-f3da-429e-bdd0-f4d9b47282e0.png">


</p>
</details> 

<details><summary>Screen is wide gamut, browser doesnt support either queries</summary>
<p>

<img width="444" alt="Screenshot 2023-03-17 at 7 38 49 AM" src="https://user-images.githubusercontent.com/1134620/225936107-875a2811-e3d2-4cd5-8188-184c8a587675.png">


</p>
</details>
