### ISSUE TITLE
Failed to load module script in Chromium browsers

### ISSUE THREAD

**Issue by dpschen** [evilmartians/oklch-picker#9]
Works in Safari though.

Console shows:

![image](https://user-images.githubusercontent.com/6173598/165914555-a7208a67-6e38-491d-a864-f760f83c9a69.png)

**Comment by ai** [comment]
Confirm. Going to debug it.

**Comment by ai** [comment]
Hot fix 78d6fbe

Will think about proper solution later.

**Comment by ai** [comment]
Fixed properly https://github.com/evilmartians/oklch-picker/commit/e96b19927e147e1c97bd35cad7cc39ce209a6df6

Thanks for the report

**Comment by dpschen** [comment]
Thanks! Interesting fix.
May I ask what the root of the problem was?

PS: Also amazing project by the way. Was in a rush when I wrote this issue. I‘m really looking forward to use oklch with real projects.

**Comment by ai** [comment]
> May I ask what the root of the problem was?

`.ts` file extension officially is not TypeScript, but MPEG container `video/mp2t`.

When Vite tries to `data:uri` TS files, it uses some library with MIME types and use `video/mp2t` instead of `application/javascript`.

I moved to stand-alone file and it solved the problem.
