### ISSUE TITLE
Charts stop updating

### ISSUE THREAD

**Issue by muddv** [evilmartians/oklch-picker#94]
Charts freeze in place or stop rendering entirely (show white canvas instead). Haven't been able to pin down exact circumstances when this happens. 

Here is a video with a Lightness chart freeze, but I think I also noticed this with Chroma.
https://user-images.githubusercontent.com/73133951/226422523-556ce914-c9a2-456a-b336-d1c1dab50318.mp4

Issue is present on latest firefox and chrome.

**Comment by ai** [comment]
Do we have an output in console when it happens?

**Comment by muddv** [comment]
No output
